import os, re
from pathlib import Path

sg_path = Path('src/site_generator.py')
code = sg_path.read_text()

new_news = """        source_clean = clean_text(s.get('source', '')).upper()
        news_html += f'''<div class="bg-slate-900/50 p-8 rounded-[2rem] border border-slate-800 shadow-lg backdrop-blur-sm flex flex-col hover:border-cyan-400 hover:shadow-[0_0_20px_rgba(34,211,238,0.15)] transition-all group"><div class="flex justify-between items-center mb-6"><span class="text-[10px] font-bold text-slate-500 uppercase tracking-widest">{source_clean}</span><span class="px-3 py-1 bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 text-[8px] font-black rounded-full uppercase">DEEP DIVE</span></div><h4 class="text-2xl font-black mb-4 leading-tight text-white group-hover:text-cyan-300 transition-colors">{title}</h4><p class="text-slate-400 text-sm mb-8 font-light leading-relaxed">{display_summary}</p><div class="mt-auto pt-5 border-t border-slate-800/50"><a href="/articles/{aid}.html" class="text-cyan-400 font-bold text-xs uppercase tracking-widest flex items-center group-hover:text-cyan-300">Read Briefing <i class="fas fa-arrow-right ml-2 transform group-hover:translate-x-1 transition-transform"></i></a></div></div>'''"""

new_tools = """                tools_html += f'''<div class="bg-slate-900/80 p-8 rounded-2xl border border-slate-800 flex flex-col hover:border-cyan-500 hover:shadow-[0_0_15px_rgba(34,211,238,0.1)] transition-all"><div class="flex justify-between items-center mb-5"><h4 class="text-xl font-bold text-white">{t_name}</h4><span class="px-2 py-1 bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-[10px] font-black rounded uppercase">{t_cat}</span></div><p class="text-slate-400 text-sm mb-8 font-light">{t_desc}</p><a href="{t_url}" target="_blank" class="mt-auto text-cyan-400 font-bold text-xs uppercase tracking-widest hover:text-cyan-300 transition-colors">Launch Tool &rarr;</a></div>'''"""

code = re.sub(r"news_html \+= f'<div class=\"bg-white.*?</div></div>'", new_news, code)
code = re.sub(r"tools_html \+= f'<div class=\"bg-slate-800.*?</div>'", new_tools, code)

old_gen = '''        html_content = html_content.replace('<table>', '<div class="overflow-x-auto"><table class="min-w-full bg-white shadow-md rounded-lg overflow-hidden my-8 border border-slate-200">')\n        html_content = html_content.replace('</table>', '</table></div>')\n        html_content = html_content.replace('<thead>', '<thead class="bg-slate-100 border-b border-slate-200">')\n        html_content = html_content.replace('<th>', '<th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-slate-500">')\n        html_content = html_content.replace('<td>', '<td class="px-6 py-4 border-t border-slate-100 text-slate-600">')\n        html_content = html_content.replace('<blockquote>', '<blockquote class="border-l-4 border-blue-500 pl-4 py-2 my-6 bg-slate-50 text-slate-600 italic">')\n        html_content = html_content.replace('<h1>', '<h1 class="text-3xl md:text-5xl font-black mb-8 text-slate-900 tracking-tight">')\n        html_content = html_content.replace('<h2>', '<h2 class="text-2xl md:text-3xl font-bold mt-12 mb-6 text-slate-800 border-b border-slate-200 pb-2">')\n        html_content = html_content.replace('<h3>', '<h3 class="text-xl font-bold mt-8 mb-4 text-slate-800">')\n        html_content = html_content.replace('<p>', '<p class="mb-6 text-lg text-slate-600 leading-relaxed">')\n        html_content = html_content.replace('<ul>', '<ul class="list-disc pl-6 mb-6 space-y-2 text-lg text-slate-600">')'''

new_gen = '''        html_content = html_content.replace('<table>', '<div class="overflow-x-auto my-12"><table class="min-w-full bg-slate-900 shadow-xl rounded-xl overflow-hidden border border-slate-800">')\n        html_content = html_content.replace('</table>', '</table></div>')\n        html_content = html_content.replace('<thead>', '<thead class="bg-slate-950 border-b border-slate-800">')\n        html_content = html_content.replace('<th>', '<th class="px-6 py-5 text-left text-xs font-black uppercase tracking-widest text-cyan-500">')\n        html_content = html_content.replace('<td>', '<td class="px-6 py-4 border-t border-slate-800 text-slate-300 font-light">')\n        html_content = html_content.replace('<blockquote>', '<blockquote class="border-l-4 border-cyan-500 pl-6 py-4 my-8 bg-cyan-900/10 text-cyan-100 italic rounded-r-lg shadow-inner">')\n        html_content = html_content.replace('<h1>', '<h1 class="text-4xl md:text-5xl font-black mb-8 text-white tracking-tight">')\n        html_content = html_content.replace('<h2>', '<h2 class="text-2xl md:text-3xl font-bold mt-16 mb-6 text-cyan-400 flex items-center tracking-tight"><span class="mr-4 text-cyan-500/30">//</span>')\n        html_content = html_content.replace('<h3>', '<h3 class="text-xl font-bold mt-10 mb-4 text-white">')\n        html_content = html_content.replace('<p>', '<p class="mb-8 text-lg text-slate-300 leading-relaxed font-light">')\n        html_content = html_content.replace('<ul>', '<ul class="list-disc pl-6 mb-8 space-y-3 text-lg text-slate-300 font-light marker:text-cyan-500">')\n        html_content = html_content.replace('<strong>', '<strong class="text-white font-bold">')'''

code = code.replace(old_gen, new_gen)
sg_path.write_text(code)
